FROM python:3.9-slim 
# Install dependencies
WORKDIR /app

COPY ../certs/ZscalerRootCA.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt
COPY ../certs/ZscalerRootCA.crt /etc/ssl/certs/zscaler-root-ca.crt

ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/zscaler-root-ca.crt

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*




COPY ./dg-backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y netcat-openbsd
COPY dg-backend/start.sh .	
RUN chmod +x start.sh
CMD ["./start.sh"]

