FROM ollama/ollama:latest

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
 
# Add Zscaler cert 
COPY ../certs/ZscalerRootCA.crt /etc/ssl/certs/zscaler-root-ca.crt
RUN update-ca-certificates
 

COPY ./dg-ollama/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]